Make the plugin work with babel 7 & babel-codemod
I believe the main issue was trying to call `path.replaceWithMultiple(…)` as well as returning the result of that call from the visitor function. I got this error:

```
Error: Unexpected return value from visitor method function newFn(path) {
          return fn.call(state, path, state);
        }
    at NodePath._call (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/path/context.js:71:13)
    at NodePath.call (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/path/context.js:38:17)
    at NodePath.visit (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/path/context.js:99:12)
    at TraversalContext.visitQueue (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitMultiple (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/context.js:89:17)
    at TraversalContext.visit (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/context.js:174:19)
    at Function.traverse.node (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/index.js:76:17)
    at NodePath.visit (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/path/context.js:106:18)
    at TraversalContext.visitQueue (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/context.js:135:18)
    at TraversalContext.visitSingle (/Users/donovan/src/babel-codemod/node_modules/@babel/traverse/lib/context.js:94:19)
```

Additionally, you can pull `types` from the babel object passed to your plugin rather than importing from a specific version of babel. This should make it easier to use with both babel 6 and babel 7.

Finally, the main file is compiled to `lib/index.js` so I made that the `main` entry in package.json so the package can be `require`d.